### ISSUE TITLE
web with iframes and shadow root.

### ISSUE THREAD

**Issue by bwecoli** [sukgu/pyshadow#10]
web with iframes and shadow root.
How to work with both at the same time?
There are iframes that contain shadow root, which in turn contain new iframes and new shadow root.

**Comment by sukgu** [comment]
@bwecoli  the first switch to iframe and then just use as usual. For multiple iframes, under shadow root, you will have to explicitly switch to those iframes after finding them using shadow methods technically.

**Comment by bwecoli** [comment]
Thank you.
I will start working on it to see if I can achieve positive results.
Best regards.
