### ISSUE TITLE
Remote driver class specification is incomplete.

### ISSUE THREAD

**Issue by bagofmice** [sukgu/pyshadow#8]
When you are assigning the typed drivers, the reference for the remoteweb_driver classname is wrong. It needs to be remote_web_driver.WebDriver to get the class name, otherwise it resolves to the module instead of the class.

main.py:30-50 

isinstance(driver, remote_web_driver)

should change to

isinstance(driver,remote_web_driver.WebDriver)

**Comment by srdgtr** [comment]
Thanks @bagofmice as that made remote web driver working for me.

**Comment by SimonMayerhofer** [comment]
@srdgtr how to use this with this fix, without @sukgu fixing it in this project? seems like he's not maintaining this project anymore.

edit: never mind. copy the project locally, making the change and import from the fixed module.
